### ISSUE TITLE
Bug: .Net Core 2.2 - Mac OSX

### ISSUE THREAD

**Issue by Baaleos** [sjh37/Effortless-.Net-Encryption#3]
Unhandled Exception: System.PlatformNotSupportedException: BlockSize must be 128 in this implementation.
   at System.Security.Cryptography.RijndaelManaged.set_BlockSize(Int32 value)
   at Effortless.Net.Encryption.Bytes.GetRijndaelManaged(Byte[] key, Byte[] iv)
   at Effortless.Net.Encryption.Bytes.GenerateIV()

256 blocksize is not supported on Mac OSX

**Comment by sjh37** [comment]
You now now the ability to specify key size & block size.
Nuget update with v3.3.0
